"""
Default experiment configuration,
NOTE: DO NOT EDIT THIS FILE DIRECTLY.
Make a new .yaml file in the configs folder.
pass this new .yaml file via the 'cfg' commandline argument to main.py, then do:
    from cfg import cfg
    cfg.merge_from_file(args.cfg)
Now you have a custom cfg file.
"""

from yacs.config import CfgNode as CN

cfg = CN()
cfg.run_name = 'default'
cfg.log_dir = ''
cfg.seed = 0
cfg.num_workers = 4

cfg.dataset = CN()
cfg.dataset.name = ''
cfg.dataset.root = ''
cfg.dataset.ann_file = ''


cfg.model = CN()
cfg.model.name = 'my_model'

cfg.model.embed_dim = 512
# vision
cfg.model.image_resolution = 336
cfg.model.vision_layers = 3  # number of layers of the vision transformer
cfg.model.vision_width = 128  # number of channels
cfg.model.vision_patch_size = 32  # patch size
# text
cfg.model.context_length = 72  # context length of the CLIP tokenizer
cfg.model.vocab_size = 49152  # vocab size of the CLIP tokenizer
cfg.model.transformer_layers = 3  # number of layers of the transformer
cfg.model.transformer_width = 512  # width of the transformer
cfg.model.transformer_heads = 4  # number of heads of the transformer


cfg.train = CN()
cfg.train.batch_size = 32
cfg.train.shuffle = True
cfg.train.lr = 1e-3
cfg.train.epochs = 100


cfg.eval = CN()
cfg.eval.model_path = ""
cfg.eval.shuffle = False
cfg.eval.batch_size = 1
